/*
 * Copyright (c) 2020 Mark A. Hunter (ACT Health)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package net.fhirfactory.pegacorn.ladon.model.status.dtcache;

public enum DTCacheActivityStatusEnum {
    DT_CACHE_ACTIVITY_RESOURCE_CREATION_START,
    DT_CACHE_ACTIVITY_RESOURCE_CREATION_IN_PROGRESS,
    DT_CACHE_ACTIVITY_RESOURCE_CREATION_FINISH,
    DT_CACHE_ACTIVITY_RESOURCE_CREATION_FAILURE,
    DT_CACHE_ACTIVITY_RESOURCE_CREATED_PAUSED,
    DT_CACHE_ACTIVITY_RESOURCE_UPDATE_START,
    DT_CACHE_ACTIVITY_RESOURCE_UPDATE_IN_PROGRESS,
    DT_CACHE_ACTIVITY_RESOURCE_UPDATE_FINISH,
    DT_CACHE_ACTIVITY_RESOURCE_UPDATE_FAILURE,
    DT_CACHE_ACTIVITY_RESOURCE_UPDATE_PAUSED,
    DT_CACHE_ACTIVITY_RESOURCE_REMOVE_START,
    DT_CACHE_ACTIVITY_RESOURCE_REMOVE_IN_PROGRESS,
    DT_CACHE_ACTIVITY_RESOURCE_REMOVE_FINISH,
    DT_CACHE_ACTIVITY_RESOURCE_REMOVE_FAILURE,
    DT_CACHE_ACTIVITY_RESOURCE_REMOVE_PAUSED,
    DT_CACHE_ACTIVITY_RESOURCE_RETRIEVED_START,
    DT_CACHE_ACTIVITY_RESOURCE_RETRIEVED_IN_PROGRESS,
    DT_CACHE_ACTIVITY_RESOURCE_RETRIEVED_FINISH,
    DT_CACHE_ACTIVITY_RESOURCE_RETRIEVED_FAILURE,
    DT_CACHE_ACTIVITY_RESOURCE_RETRIEVED_PAUSED,
    DT_CACHE_ACTIVITY_RESOURCE_SYNCHRONISING,
    DT_CACHE_ACTIVITY_RESOURCE_LOADING_START,
    DT_CACHE_ACTIVITY_RESOURCE_LOADING_IN_PROGRESS,
    DT_CACHE_ACTIVITY_RESOURCE_LOADING_FINISH,
    DT_CACHE_ACTIVITY_RESOURCE_LOADING_FAILURE,
    DT_CACHE_ACTIVITY_RESOURCE_INSYNC,

}
